name: 解码并生成新文件

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'  # 可选：每天UTC时间0点/6点/12点/18点自动运行

env:
  SOURCE_URL: "https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2"  # 替换为你的URL
  TARGET_FILE: "v2"

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:  # 关键权限声明
      contents: write  # 允许推送代码
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 推送所需的权限
          persist-credentials: true

      - name: Fetch and decode content
        run: |
          set -euxo pipefail

          # 获取内容并清理换行符
          encoded_content=$(curl -sL "$SOURCE_URL" | tr -d '\n')

          # Base64解码并保存
          echo "$encoded_content" | base64 -d > "$TARGET_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.TARGET_FILE }}
          
          # 仅当有变化时提交
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-update: Decoded content from ${{ env.SOURCE_URL }}"
            git push
          else
            echo "No changes to commit."
          fi
